#include "tcl_writer.h"

#include <cstdio>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace legalizer {

std::string formatMicron(double value) {
  std::ostringstream oss;
  oss << std::fixed << std::setprecision(9) << value;
  std::string s = oss.str();
  while (s.size() > 1 && s.back() == '0') {
    s.pop_back();
  }
  if (!s.empty() && s.back() == '.') {
    s.pop_back();
  }
  if (s == "-0") {
    s = "0";
  }
  return s;
}

bool isSafeTclBracedName(const std::string &name) {
  if (name.empty()) {
    return false;
  }
  for (char c : name) {
    if (c == '{' || c == '}' || c == '\n' || c == '\r') {
      return false;
    }
  }
  return true;
}

WriteResult writePlacementTcl(const PlacementModel &model, const std::string &path) {
  WriteResult result;
  for (const Cell &cell : model.cells) {
    if (!cell.has_placement) {
      result.error = "refusing to write unplaced cell '" + cell.name + "'";
      return result;
    }
    if (!isSafeTclBracedName(cell.name)) {
      result.error = "instance name is not safe for braced Tcl output: '" + cell.name + "'";
      return result;
    }
  }

  std::string tmp_path = path + ".tmp";
  {
    std::ofstream out(tmp_path);
    if (!out) {
      result.error = "cannot open output file '" + tmp_path + "'";
      return result;
    }
    out << "# Generated by Legalizer. Contains only placement commands.\n";
    for (const Cell &cell : model.cells) {
      out << "place_cell -inst_name {" << cell.name << "} -orient R0 -origin {"
          << formatMicron(dbuToMicron(model, cell.placed.llx)) << " "
          << formatMicron(dbuToMicron(model, cell.placed.lly)) << "}\n";
    }
    if (!out) {
      result.error = "failed while writing '" + tmp_path + "'";
      return result;
    }
  }

  if (std::rename(tmp_path.c_str(), path.c_str()) != 0) {
    std::remove(tmp_path.c_str());
    result.error = "failed to replace output file '" + path + "'";
    return result;
  }
  result.ok = true;
  return result;
}

}  // namespace legalizer
